#    "$Name:  $";
#    "$Header:  $";
# ============================================================================
#
# file :        TestWriter.py
#
# description : Python source for the TestWriter and its commands.
#                The class is derived from Device. It represents the
#                CORBA servant object which will be accessed from the
#                network. All commands which can be executed on the
#                TestWriter are implemented in this file.
#
# project :     TANGO Device Server
#
# $Author:  $
#
# $Revision:  $
#
# $Log:  $
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
# ============================================================================
#          This file is generated by POGO
#    (Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
# ============================================================================
#

import sys

try:
    import tango
except Exception:
    import PyTango as tango

# =================================================================
#   TestWriter Class Description:
#
#         My Simple Server
#
# =================================================================
#     Device States Description:
#
#   DevState.ON :  Server On
# =================================================================


class NXSDataWriter(tango.Device_4Impl):

    # --------- Add you global variables here --------------------------

    # ------------------------------------------------------------------
    #    Device constructor
    # ------------------------------------------------------------------

    def __init__(self, cl, name):
        tango.Device_4Impl.__init__(self, cl, name)

        self.attr_value = ""
        self.attr_AcqChannelList = []
        self.attr_MeasurementGroupList = []
        self.attr_ExpChannelList = []
        self.attr_MotorList = []
        NXSDataWriter.init_device(self)

    # ------------------------------------------------------------------
    #    Device destructor
    # ------------------------------------------------------------------
    def delete_device(self):
        """ """

    # ------------------------------------------------------------------
    #    Device initialization
    # ------------------------------------------------------------------

    def init_device(self):
        self.set_state(tango.DevState.ON)
        self.get_device_properties(self.get_device_class())

    # ------------------------------------------------------------------
    #    Always excuted hook method
    # ------------------------------------------------------------------
    def always_executed_hook(self):
        """ """

#
# =================================================================
#
#    TestWriter read/write attribute methods
#
# =================================================================

# =================================================================
#
#    TestWriter command methods
#
# =================================================================
    #
    # ------------------------------------------------------------------
    #    SetState command:
    #
    #    Description: Set state of tango device
    #
    #    argin: DevString     tango state
    # ------------------------------------------------------------------

    def SetState(self, state):
        if state == "RUNNING":
            self.set_state(tango.DevState.RUNNING)
        elif state == "FAULT":
            self.set_state(tango.DevState.FAULT)
        elif state == "ALARM":
            self.set_state(tango.DevState.ALARM)
        else:
            self.set_state(tango.DevState.ON)


# =================================================================
#
#    WriterClass class definition
#
# =================================================================
class NXSDataWriterClass(tango.DeviceClass):

    #    Class Properties
    class_property_list = {
    }

    #    Device Properties
    device_property_list = {
    }

    #    Command definitions
    cmd_list = {
        'SetState':
        [[tango.DevString, "ScalarString"],
         [tango.DevVoid, ""]],
    }

    #    Attribute definitions
    attr_list = {
    }

# ------------------------------------------------------------------
#    WriterClass Constructor
# ------------------------------------------------------------------
    def __init__(self, name):
        tango.DeviceClass.__init__(self, name)
        self.set_type(name)


# =================================================================
#
#    Writer class main method
#
# =================================================================
if __name__ == '__main__':
    try:
        argv = list(sys.argv)
        argv[0] = "NXSDataWriter"
        py = tango.Util(argv)
        py.add_class(NXSDataWriterClass, NXSDataWriter)

        U = tango.Util.instance()
        U.server_init()
        U.server_run()

    except tango.DevFailed as e:
        print('-------> Received a DevFailed exception: %s' % e)
    except Exception as e:
        print('-------> An unforeseen exception occured.... %s' % e)
