name: Test Package

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * 1'

jobs:

  flake8_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  # dpkg_tests:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       os: [debian13, debian12, ubuntu26.04, ubuntu24.04]
  #       test: [extrasettings, extraserver, basicserver, basicsettings, basic]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v2
  #     - name: Update bash files
  #       run: |
  #         chmod +x .ci/run.sh
  #         chmod +x .ci/install.sh
  #     - name: Build the docker
  #       env:
  #         OS: ${{ matrix.os }}
  #       run: docker build -t ndts .ci/${OS}_py3
  #     - name: Run the docker
  #       run: docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts
  #     - name: install tango
  #       env:
  #         OS: ${{ matrix.os }}
  #       run: .ci/install.sh ${OS} 3
  #     - name: run tests
  #       env:
  #         TEST: ${{ matrix.test }}
  #       run: .ci/run.sh ${TEST} 3
  #     - name: Stop the docker
  #       run: |
  #            docker exec  --user root ndts  /bin/bash -c "chown -R 1001 /home/tango "
  #            docker container stop ndts

  pixi_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian13, ubuntu26.04]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - name: Update bash files
        run: |
          chmod +x .ci/run_pixi.sh
          chmod +x .ci/install_tango.sh
      - name: Build the docker
        env:
          OSYS: ${{ matrix.os }}
        run: docker build -t ndts .ci/${OSYS}_pixi
      - name: Run the docker
        run: docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts
      - name: Install tango
        env:
          OSYS: ${{ matrix.os }}
        run: .ci/install_tango.sh ${OSYS}
      - name: Run pixi and tests
        run: .ci/run_pixi.sh
      - name: Stop the docker
        run: |
             docker exec  --user root ndts  /bin/bash -c "chown -R 1001 /home/tango "
             docker container stop ndts
